import type { AdvancedMetronomeConfig } from "./advanced-metronome";

export const initialConfig: AdvancedMetronomeConfig = {
  units: [
    {
      id: "b",
      name: "Beats.",
      length: 1,
      lengthUnit: "beat",
    },
    {
      id: "e1",
      name: "Exercise 1.",
      length: 2,
      lengthUnit: "b",
    },
    {
      id: "r1",
      name: "4 repetitions of exercise 1.",
      length: 4,
      lengthUnit: "e1",
    },
    {
      id: "s1",
      name: "Set of 4 repetitions of execrice 1.",
      length: 4,
      lengthUnit: "r1",
    },
    {
      id: "5s1",
      name: "5 sets of exercise 1.",
      length: 4,
      lengthUnit: "s1",
    },
  ],
  tempos: [
    {
      id: "w",
      name: "warmup",
      bpm: 100,
    },
    {
      id: "e",
      name: "exerice",
      bpm: 130,
    },
  ],
  parts: [
    {
      id: "e1",
      name: "5 semitones up",
      tempoId: "e",
      length: 4,
      lengthUnitId: "5s1",
      repetitions: 3,
      pauseLength: 2,
      pauseLengthUnitId: "r1",
    },
    {
      id: "e1",
      name: "5 semitones down",
      tempoId: "e",
      length: 4,
      lengthUnitId: "5s1",
      repetitions: 3,
      pauseLength: 2,
      pauseLengthUnitId: "r1",
    },
    {
      id: "e1",
      name: "5 semitones up and down",
      tempoId: "e",
      length: 4,
      lengthUnitId: "5s1",
      repetitions: 3,
      pauseLength: 2,
      pauseLengthUnitId: "r1",
    },
    {
      id: "e1",
      name: "2 strings 5 notes up",
      tempoId: "e",
      length: 4,
      lengthUnitId: "5s1",
      repetitions: 3,
      pauseLength: 2,
      pauseLengthUnitId: "r1",
    },
    {
      id: "e1",
      name: "2 strings full",
      tempoId: "e",
      length: 4,
      lengthUnitId: "5s1",
      repetitions: 3,
      pauseLength: 2,
      pauseLengthUnitId: "r1",
    },
    {
      id: "e1",
      name: "2 strings up & down",
      tempoId: "e",
      length: 4,
      lengthUnitId: "5s1",
      repetitions: 3,
      pauseLength: 2,
      pauseLengthUnitId: "r1",
    },
  ],
};
